language: python
python:
  - "2.7"
sudo: false
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
  matrix:
    - TOX_ENV=py26,
    - TOX_ENV=py27,
    - TOX_ENV=py33,
    - TOX_ENV=py34,
    - TOX_ENV=with_iso8601,
    - TOX_ENV=flake8
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - "travis_retry pip install setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
